include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '_poc/**'
    - build/**
    - android/**
    - linux/**
    - macos/**

linter:
  rules:
    prefer_single_quotes: true
    avoid_print: true
